[2021-05-20T15:22:15.678Z] QueryFailedError: column FeedbackModel.category does not exist
    at new QueryFailedError (/media/gabriellopes/HD/drive/www/feedbackio/api/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at PostgresQueryRunner.<anonymous> (/media/gabriellopes/HD/drive/www/feedbackio/api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:248:31)
    at step (/media/gabriellopes/HD/drive/www/feedbackio/api/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/media/gabriellopes/HD/drive/www/feedbackio/api/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/media/gabriellopes/HD/drive/www/feedbackio/api/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

